name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:

jobs:
  scalafmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./bin/scalafmt --test
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        jvm: ['adopt:1.8.0-292', 'adopt:1.11.0.11', 'temurin:1.17.0.3']
    name: Test on ${{ matrix.os }} -- ${{ matrix.jvm }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Checkout java-debug
      uses: actions/checkout@v3
      with:
        repository: scalacenter/java-debug
        ref: debug
        path: java-debug
    - uses: coursier/setup-action@v1.2.0
      with:
        jvm: ${{ matrix.jvm }}
        app: sbt
    - run: ./mvnw install
      working-directory: java-debug/com.microsoft.java.debug.core 
    - name: Unit tests
      run: sbt test
      shell: bash
