name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:

jobs:
  scalafmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./bin/scalafmt --test
  cross-compilation:
    name: Cross Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: coursier/setup-action@v1.3.3
        with:
          apps: sbt
      - run: sbt +Test/compile
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        jvm: ['adoptium:1.8.0-372', 'adoptium:1.11.0.19', 'adoptium:1.17.0.7']
        include:
          - os: ubuntu-latest
            jvm: 'adoptium:1.20.0.1'
    name: Test on ${{ matrix.os }} -- ${{ matrix.jvm }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: coursier/setup-action@v1.3.3
      with:
        jvm: ${{ matrix.jvm }}
        apps: sbt
    - name: Unit tests
      run: sbt test
      shell: bash
    - name: Scripted sbt tests
      run: sbt sbtPlugin/scripted
      shell: bash
      if: ${{ matrix.jvm != 'adoptium:1.20.0.1' }}
