name: Continuous Integration
on:
  push:
  pull_request:

jobs:
  scalafmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1.2.0-M3
      - run: ./bin/scalafmt --test
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        jdk: [8, 11, 'temurin:1.17']
    name: Test on ${{ matrix.os }} -- ${{ matrix.jdk }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: coursier/setup-action@v1.2.0-M3
      with:
        jvm: ${{ matrix.jdk }}
        apps: sbt
    - name: Cross-publish the expression evaluator
      run: sbt +expressionCompiler/publishLocal
    - name: Test core project
      run: sbt core/test
    - name: Test sbt plugin
      run: sbt sbtPlugin/scripted
